const template = opts => {
  return `
  <!DOCTYPE html>
  <html>
    <head>
      <title>Podcasts</title>
      <meta name="description" content="Top podcasts">
      <!-- Bootstrap -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
      <!-- Custom CSS -->
      <link rel="stylesheet" href="/assets/styles/main.css" />
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">


    </head>
    <body>
      <div id="root">${opts.body}</div>
    </body>
    <script>
      window.__initialState = ${opts.initialState}
    </script>
    <!-- Client bundle generated by webpack -->
    <script src='/assets/client.bundle.js'></script>
  </html>
  `;
};

module.exports = template;
